data-test attrs for components
Lambda-IT/parlamentsdienste-components pull request #118
Opened 2022-01-13 14:36 UTC by thomasschneiter

2022-01-14 07:10 UTC, matthiasbaldi commented on src/components/pd-checkbox/pd-checkbox.tsx
> +                    />
öhm lol 😏😅

2022-01-14 07:36 UTC, matthiasbaldi requested changes
Some small stuff, may not everything is a task.
We can further discuss it.

2022-01-14 07:36 UTC, matthiasbaldi commented on src/components/pd-combobox/pd-combobox.tsx
> +                            data-test={`pd-combobox-item-${comboboxItem.id}`}
I wonder is it a good pattern to add the id on the `data-test` attribute?
As I know we discussed it as it is, but I'm not sure.
My point is, can we assume that the test writer knows about the ids of that element? And is it simple enough to get it?
Would it be possibly better, that the framework user would set such an id tag on the outer component?
What do you think?

2022-01-14 07:36 UTC, matthiasbaldi commented on src/components/pd-dropdown/pd-dropdown.tsx
> +                data-test={`pd-dropdown-item-${item.id}`}
see combobox feedback

2022-01-14 07:36 UTC, matthiasbaldi commented on src/components/pd-menu/pd-menu.tsx
> +                        data-test="pd-menu-button"
Do we need below (line 110) may also a data-test attribute, to reach it easier for a click?

https://github.com/Lambda-IT/parlamentsdienste-components/blob/2941b7c59fd1b22fdac18639fb9880b8d8b1fe98/src/components/pd-menu/pd-menu.tsx#L109-L119

2022-01-14 07:36 UTC, matthiasbaldi commented on src/components/pd-search/pd-search.tsx
>                          <button class="pd-search-clear" onClick={this.reset} tabindex="-1">
consider to give the buttons here also some test attrs.
see table-filter component

2022-01-14 07:36 UTC, matthiasbaldi commented on src/components/pd-table-filter/pd-table-filter.tsx
>                          <button class="pd-table-search-button" onClick={this.onSearch} tabindex="-1">
Just a question, why sou set a data-test attr  on the input, on the following buttons, but not on the search button?
In my opinion it is not really necessary because you can also start the filter by hitting the Enter button so its not that relevant.

2022-01-14 07:36 UTC, matthiasbaldi commented on src/components/pd-table/pd-table.tsx
> +                            data-test={`pd-table-header-text-col-${i}`}
Is a attr not even more important on the direct parent?
Because there are the click handler attached.

2022-01-17 15:35 UTC, thomasschneiter commented on src/components/pd-menu/pd-menu.tsx
> +                        data-test="pd-menu-button"
I think you can click the menu item itself in the slot and don't have to click the menu for this onClick to trigger?
Btw. tabIndex=-1 on a div is probably not needed.

2022-01-17 15:44 UTC, thomasschneiter commented on src/components/pd-table-filter/pd-table-filter.tsx
>                          <button class="pd-table-search-button" onClick={this.onSearch} tabindex="-1">
I just didn't add attributes to buttons which are not focus-able. But since there's a onSearch/reset on them they could have an attribute.

2022-01-17 16:17 UTC, thomasschneiter commented on src/components/pd-table/pd-table.tsx
> +                            data-test={`pd-table-header-text-col-${i}`}
I agree

2022-01-18 12:26 UTC, matthiasbaldi commented on src/components/pd-combobox/pd-combobox.tsx
> +                            data-test={`pd-combobox-item-${comboboxItem.id}`}
Ya that makes sense.
And also to use the unique identifier instead of an index, because an index is already given by the HTML selector.

2022-01-18 12:27 UTC, matthiasbaldi commented on src/components/pd-menu/pd-menu.tsx
> +                        data-test="pd-menu-button"
hmmm right. This was the discussion which element could be clicked without any selection in the shadow dom.

2022-01-18 13:26 UTC, merged