feat(menu): add label text for menu
Lambda-IT/parlamentsdienste-components pull request #51
Opened 2021-05-04 12:58 UTC by matthiasbaldi

#46
- added menu label
- set correct colors

2021-05-06 07:32 UTC, thomasschneiter requested changes

2021-05-06 07:32 UTC, thomasschneiter commented on src/components/pd-menu/pd-menu.scss
> +    height: 38px;
use 2.375rem;

2021-05-06 07:32 UTC, thomasschneiter commented on src/components/pd-menu/pd-menu.scss
> +        line-height: 38px;
use 2.375rem;

2021-05-06 07:32 UTC, thomasschneiter commented on src/components/pd-menu/pd-menu.tsx
> +      console.log('renderLabel', this.label)
remove

2021-05-06 14:08 UTC, matthiasbaldi commented
- [ ] Also add label to pd-table (menu in header)

2021-05-10 08:32 UTC, thomasschneiter commented on src/components/pd-menu/pd-menu.tsx
> +                <div class={{ 'pd-menu': true, 'pd-menu-iverted': this.invertColor }}>
`iverted` In case you want to fix it ;-)

2021-05-10 08:53 UTC, thomasschneiter commented on src/components/pd-menu/pd-menu.scss
> +
Maybe remove left/right-padding of .pd-menu-button, 
`padding-left: 0; padding-right: 0;`
otherwise the text does not align with other elements.

![image](https://user-images.githubusercontent.com/59556890/117632941-d8b98f80-b17d-11eb-9522-c1ca84265513.png)

![image](https://user-images.githubusercontent.com/59556890/117633016-eb33c900-b17d-11eb-93ca-ebae0b33f5f4.png)

2021-05-10 09:01 UTC, thomasschneiter approved these changes

2021-05-11 10:05 UTC, merged